import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [increments, setIncrements] = useState(14);
  const [daysToTolerance, setDaysToTolerance] = useState(4);
  const [daysToReset, setDaysToReset] = useState(7);

  const stimulatedDays = increments * daysToTolerance;
  const stimulatedMonths = stimulatedDays / 30;

  const cycleLengthDays = Number(stimulatedDays) + Number(daysToReset);
  const cycleLengthMonths = cycleLengthDays / 30;
  const cyclesInYear = 365 / cycleLengthDays;

  return (
    <div className={styles.container}>
      <Head>
        <title>Caffeine Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1
          className={styles.title}
          onChange={(e) => setIncrements(e.target.value)}
        >
          Caffeine Calculator
        </h1>

        
          <label>
            How many increments of caffeine amounts do you have? (increments meaning 25mg/50mg/75mg so eg. 10/11)
          </label>
          <input
            style={{ display: "block", align: "center" }}
            type="text"
            value={increments}
            onChange={(e) => setIncrements(e.target.value)}
          ></input>

          <label>
            How many days can you stay on one increment before acquiring
            tolerance?
          </label>
          <input
            style={{ display: "block" }}
            type="text"
            value={daysToTolerance}
            onChange={(e) => setDaysToTolerance(e.target.value)}
          ></input>

          <label>How many days does it take for you to reset caffeine tolerance?</label>
          <input
            style={{ display: "block" }}
            type="text"
            value={daysToReset}
            onChange={(e) => setDaysToReset(e.target.value)}
          ></input>
      

        <p>
          That means {stimulatedDays} days of increasing caffeine dosage every{" "}
          {daysToTolerance} days until having to spend {daysToReset} days
          without caffeine to reset your tolerance. This cycle will reset every{" "}
          {cycleLengthMonths.toFixed(1)} months.
        </p>

        <p> Stimulated days / cycle: {stimulatedDays} </p>
        <p> Stimulated months / cycle: {stimulatedMonths.toFixed(1)} </p>
        <p> Cycles in year: {cyclesInYear.toFixed(1)} </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://spacelutt.com/choices"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Space
        </a>
      </footer>
    </div>
  );
}
